# Generated by Django 6.0.1 on 2026-01-28 13:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nume')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Cod')),
                ('address', models.TextField(blank=True, verbose_name='Adresa')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Locatie',
                'verbose_name_plural': 'Locatii',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('officer', 'Ofiter de Serviciu')], default='officer', max_length=10, verbose_name='Rol')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('location', models.ForeignKey(blank=True, help_text='Locatia asignata pentru Ofiteri de Serviciu. Gol pentru Administratori.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='officers', to='core.location', verbose_name='Locatie')),
            ],
            options={
                'verbose_name': 'Utilizator',
                'verbose_name_plural': 'Utilizatori',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_id', models.CharField(blank=True, help_text='ID extern (ex. din sistemul HR)', max_length=50, verbose_name='ID Extern')),
                ('nume', models.CharField(max_length=200, verbose_name='Nume')),
                ('departament', models.CharField(blank=True, max_length=100, verbose_name='Departament')),
                ('activ', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(help_text='Locatia unde este inregistrat angajatul', on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.location', verbose_name='Locatie')),
            ],
            options={
                'verbose_name': 'Angajat',
                'verbose_name_plural': 'Angajati',
                'ordering': ['nume'],
                'indexes': [models.Index(fields=['nume'], name='core_employ_nume_9fd18d_idx'), models.Index(fields=['departament'], name='core_employ_departa_acd5f4_idx'), models.Index(fields=['location', 'activ'], name='core_employ_locatio_c1c3b6_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('employee', 'Angajat'), ('vehicle', 'Vehicul')], max_length=10, verbose_name='Tip entitate')),
                ('entity_id', models.PositiveIntegerField(verbose_name='ID Entitate')),
                ('direction', models.CharField(choices=[('IN', 'Intrare'), ('OUT', 'Iesire')], max_length=3, verbose_name='Directie')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data si ora')),
                ('location', models.ForeignKey(help_text='Locatia unde a avut loc evenimentul', on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='core.location', verbose_name='Locatie')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_entries', to=settings.AUTH_USER_MODEL, verbose_name='Inregistrat de')),
            ],
            options={
                'verbose_name': 'Inregistrare jurnal',
                'verbose_name_plural': 'Inregistrari jurnal',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', '-timestamp'], name='core_logent_entity__4e4c9b_idx'), models.Index(fields=['location', '-timestamp'], name='core_logent_locatio_1e2f54_idx'), models.Index(fields=['direction', '-timestamp'], name='core_logent_directi_d90602_idx'), models.Index(fields=['-timestamp'], name='core_logent_timesta_ca4ad7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_number', models.CharField(max_length=20, verbose_name='Numar inmatriculare')),
                ('descriere', models.CharField(blank=True, max_length=200, verbose_name='Descriere')),
                ('proprietar', models.CharField(blank=True, max_length=200, verbose_name='Proprietar')),
                ('activ', models.BooleanField(default=True, verbose_name='Activ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(help_text='Locatia unde este inregistrat vehiculul', on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='core.location', verbose_name='Locatie')),
            ],
            options={
                'verbose_name': 'Vehicul',
                'verbose_name_plural': 'Vehicule',
                'ordering': ['plate_number'],
                'indexes': [models.Index(fields=['plate_number'], name='core_vehicl_plate_n_a0165d_idx'), models.Index(fields=['location', 'activ'], name='core_vehicl_locatio_3bb1f0_idx')],
                'constraints': [models.UniqueConstraint(fields=('location', 'plate_number'), name='unique_vehicle_plate_per_location')],
            },
        ),
    ]
